
package ro.pub.cs.aipi.lab07.businesslogic;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookManager", targetNamespace = "http://businesslogic.lab07.aipi.cs.pub.ro/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookManager {


    /**
     * 
     * @return
     *     returns java.util.List<ro.pub.cs.aipi.lab07.businesslogic.BookInformation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBooksList", targetNamespace = "http://businesslogic.lab07.aipi.cs.pub.ro/", className = "ro.pub.cs.aipi.lab07.businesslogic.GetBooksList")
    @ResponseWrapper(localName = "getBooksListResponse", targetNamespace = "http://businesslogic.lab07.aipi.cs.pub.ro/", className = "ro.pub.cs.aipi.lab07.businesslogic.GetBooksListResponse")
    @Action(input = "http://businesslogic.lab07.aipi.cs.pub.ro/BookManager/getBooksListRequest", output = "http://businesslogic.lab07.aipi.cs.pub.ro/BookManager/getBooksListResponse")
    public List<BookInformation> getBooksList();

    /**
     * 
     * @param stockpile
     * @return
     *     returns java.util.List<ro.pub.cs.aipi.lab07.businesslogic.BookInformationDetailed>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBooksListWithStockpile", targetNamespace = "http://businesslogic.lab07.aipi.cs.pub.ro/", className = "ro.pub.cs.aipi.lab07.businesslogic.GetBooksListWithStockpile")
    @ResponseWrapper(localName = "getBooksListWithStockpileResponse", targetNamespace = "http://businesslogic.lab07.aipi.cs.pub.ro/", className = "ro.pub.cs.aipi.lab07.businesslogic.GetBooksListWithStockpileResponse")
    @Action(input = "http://businesslogic.lab07.aipi.cs.pub.ro/BookManager/getBooksListWithStockpileRequest", output = "http://businesslogic.lab07.aipi.cs.pub.ro/BookManager/getBooksListWithStockpileResponse")
    public List<BookInformationDetailed> getBooksListWithStockpile(
        @WebParam(name = "stockpile", targetNamespace = "")
        int stockpile);

}
