
package ro.pub.cs.aipi.lab07.businesslogic;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WriterManager", targetNamespace = "http://businesslogic.lab07.aipi.cs.pub.ro/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WriterManager {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteWritersWithoutBooks", targetNamespace = "http://businesslogic.lab07.aipi.cs.pub.ro/", className = "ro.pub.cs.aipi.lab07.businesslogic.DeleteWritersWithoutBooks")
    @ResponseWrapper(localName = "deleteWritersWithoutBooksResponse", targetNamespace = "http://businesslogic.lab07.aipi.cs.pub.ro/", className = "ro.pub.cs.aipi.lab07.businesslogic.DeleteWritersWithoutBooksResponse")
    @Action(input = "http://businesslogic.lab07.aipi.cs.pub.ro/WriterManager/deleteWritersWithoutBooksRequest", output = "http://businesslogic.lab07.aipi.cs.pub.ro/WriterManager/deleteWritersWithoutBooksResponse")
    public int deleteWritersWithoutBooks();

    /**
     * 
     * @param numberOfBooksAlone
     * @param numberOfBooksCollaboration
     * @param numberOfBooksTotal
     * @return
     *     returns java.util.List<ro.pub.cs.aipi.lab07.businesslogic.WriterInformation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWritersBibliography", targetNamespace = "http://businesslogic.lab07.aipi.cs.pub.ro/", className = "ro.pub.cs.aipi.lab07.businesslogic.GetWritersBibliography")
    @ResponseWrapper(localName = "getWritersBibliographyResponse", targetNamespace = "http://businesslogic.lab07.aipi.cs.pub.ro/", className = "ro.pub.cs.aipi.lab07.businesslogic.GetWritersBibliographyResponse")
    @Action(input = "http://businesslogic.lab07.aipi.cs.pub.ro/WriterManager/getWritersBibliographyRequest", output = "http://businesslogic.lab07.aipi.cs.pub.ro/WriterManager/getWritersBibliographyResponse")
    public List<WriterInformation> getWritersBibliography(
        @WebParam(name = "numberOfBooksTotal", targetNamespace = "")
        int numberOfBooksTotal,
        @WebParam(name = "numberOfBooksAlone", targetNamespace = "")
        int numberOfBooksAlone,
        @WebParam(name = "numberOfBooksCollaboration", targetNamespace = "")
        int numberOfBooksCollaboration);

}
